AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Managed Microsoft AD Stack'
Parameters:
  Name:
    Type: String
    Default: corp.demoftp.com
  Password:
    Type: String
    MinLength: 8
    MaxLength: 20
    NoEcho: true
  ShortName:
    Type: String
    Default: corp
    MinLength: 8
    MaxLength: 20
Resources:
  VpcStack:
      Type: 'AWS::CloudFormation::Stack'
      DeletionPolicy: Delete
      Properties:
        TemplateURL: >-
          https://raw.githubusercontent.com/aws-samples/toolkit-for-aws-transfer-family/main/solutions/custom-idp/vpc-cfn.yaml
        Parameters:
          EnvironmentName: !Ref AWS::StackName
  ManagedAD: 
    Type: AWS::DirectoryService::MicrosoftAD
    Properties: 
      Name: !Ref Name
      Password: !Ref Password
      ShortName: !Ref ShortName
      Edition: Standard
      CreateAlias: true
      VpcSettings: 
        SubnetIds: 
          !Ref VpcStack.Outputs.PrivateSubnets
        VpcId: 
          !Ref VpcStack.Outputs.VPC

Outputs:
  DirectoryID:
    Description: ID of the MS Directory
    Value: !Ref ManagedAD
  PrimaryDNS:
    Description: DNS IPs of the MS Directory
    Value: !Select [ '0', !GetAtt ManagedAD.DnsIpAddresses ]
  SecondaryDNS:
    Description: DNS IPs of the MSDirectory
    Value: !Select [ '1', !GetAtt ManagedAD.DnsIpAddresses ]
  DirectoryAlias:
    Description: URL for the alias
    Value: !GetAtt ManagedAD.Alias
  VpcId:
    Description: Vpc Id
    Value: !GetAtt VpcStack.Outputs.VPC
  SubnetPrivateSubnets:
    Description: Private Subnets
    Value: !GetAtt VpcStack.Outputs.PrivateSubnets
  SubnetPublicSubnets:
    Description: Public Subnets
    Value: !GetAtt VpcStack.Outputs.PublicSubnets
