---
name: Enhancement request
about: Suggest an idea to enhance some existing feature
title: '[Enhancement]: TITLE HERE'
labels: ["enhancement", "Needs Triage"]
assignees: ''

---

**Is your idea related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. "Add the ability to do xyz with identity provider abc in the custom IdP solution."

**Describe the solution you'd like**
A clear and concise description of what you are expecting. Please be as specific as possible with requirements. If you have an idea for how to implement the enhancement from a technical point of view, please also provide it here.

*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*