---
name: "Question"
about: "Ask general questions using this form. Please ask with as many useful details as possible."
title: "[QUESTION] <title>"
labels: ["question", "Needs Triage"]

---

*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*