AWSTemplateFormatVersion: '2010-09-09'
Description: 'This template deploys AWS Managed Microsoft AD Stack and a VPC with subnets'
Parameters:
  DirectoryDNSName:
    Description: Microsoft ActiveDirectory DNS Name
    Type: String
    Default: corp.demoftp.com
  DirectoryAdminPassword:
    Description: Microsoft ActiveDirectory Administrator Password
    Type: String
    MinLength: 5
    MaxLength: 20
    NoEcho: true
  DirectoryBIOSName:
    Description: Microsoft ActiveDirectory BIOS Name
    Type: String
    Default: corp
    MinLength: 3
    MaxLength: 20
  VpcPrivateSubnet0:
    Description: PrivateSubnet that the ActiveDirectory will be deployed
    Type: String
    MinLength: 3
  VpcPrivateSubnet1:
    Description: PrivateSubnet that the ActiveDirectory will be deployed
    Type: String
    MinLength: 3
  VpcId:
    Description: VPC Id
    Type: String
    MinLength: 3

Resources:
  ManagedAD: 
    Type: AWS::DirectoryService::MicrosoftAD
    Properties: 
      Name: !Ref DirectoryDNSName
      Password: !Ref DirectoryAdminPassword
      ShortName: !Ref DirectoryBIOSName
      Edition: Standard
      CreateAlias: true
      VpcSettings: 
        SubnetIds: 
          - !Ref VpcPrivateSubnet0
          - !Ref VpcPrivateSubnet1
        VpcId: 
          !Ref VpcId

Outputs:
  DirectoryID:
    Description: ID of the MS Directory
    Value: !Ref ManagedAD
  PrimaryDNS:
    Description: Primary DNS IPs of the MS Directory
    Value: !Select [ '0', !GetAtt ManagedAD.DnsIpAddresses ]
  SecondaryDNS:
    Description: Secondary DNS IPs of the MSDirectory
    Value: !Select [ '1', !GetAtt ManagedAD.DnsIpAddresses ]
  DirectoryAlias:
    Description: AD alias
    Value: !GetAtt ManagedAD.Alias
  