name: Static Checking

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
    - "custom-idp/**"      
  pull_request:
    branches:
      - main
    paths:
    - "custom-idp/**"

permissions:
  contents: read

jobs:
  Check:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruff
      - name: ruff format check
        run: ruff format --check ./custom-idp
      - name: ruff check
        run: ruff check --output-format=github ./custom-idp
